version: "3.7"

services:

  callcenter.ingins.com:
    image: call-center:latest
    hostname: callcenter
    domainname: ingins.com
    ports:
      - "8383:8383"
      - "5005:5005"
    expose:
      - 8080
    depends_on:
      - postgres
    environment:
      SPRING_PROFILES_ACTIVE: development

  postgres:
    image: postgres
    container_name: postgres
    environment:
      POSTGRES_DB: call_center
      POSTGRES_USER: ingins
      POSTGRES_PASSWORD: secret
    ports:
      - "5432:5432"
    expose:
      - 5432